### PR TITLE
Merge branch 'Mobile' into 'Main' 

### PR DESCRIPTION
**Pull request by yavuzsa**
For some time our development have been done in 'Mobile' branch.
This is an all encompassing pull request that included contributions from all team members
I kindly request 1 person from each development sub team to review and approve the changes.

### CODE REVIEW

**Comment by yavuzsa** [comment]
Looks good to me. Lets do more frequent merges next time.

**Review by JohnsL-U — APPROVED** [review]
It seems well structured and clean. Every aspect of the project is seamlessly integrated!

**Comment by sananeminli** [comment]
All code has been checked, and everything is working fine.

**Review by sananeminli — APPROVED** [review]

**Review by Ali-Hakan — APPROVED** [review]
The frontend and backend updates can be rebased and merged without any issues.

**Review by BurakKocak99 — COMMENTED** [review]
Approved.

**Review by erhan-yasar — COMMENTED** [review]
Everything looks great.

**Review by erhan-yasar — APPROVED** [review]

**Pull request merged**
